version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myappuser
      POSTGRES_PASSWORD: myapppassword # Set your desired password here
      POSTGRES_DB: myappdb