apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  containers:
    - name: web-app
      image: chirag0101010101/open-flights_web:latest
      ports:
        - containerPort: 8080
      env:
        - name: RAILS_ENV
          value: production
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP